echo ...
echo ... Questo comando serve a rinnovare la chiave ed il certificato di firma e di criptografica utilizzati da spid-oidc-check-op.
echo ... Verrà ora richiesto di inserire la password per la chiave privata di firma, almeno 6 caratteri
echo ... 
openssl req -x509 -sha256 -days 730 -newkey rsa:2048 -keyout spid-oidc-check-op-sig.key -out spid-oidc-check-op-sig.crt
echo ... 
echo ... Ora si dovrà reinserire la password per rimuoverla dalla chiave
echo ...
openssl rsa -in spid-oidc-check-op-sig.key -out spid-oidc-check-op-sig.key
echo ...
echo ... Chiave e certificato di firma sono stati salvati rispettivamente in spid-oidc-check-op-sig.key e spid-oidc-check-op-sig.crt
echo ...
echo ...
echo ... Verrà ora richiesto di inserire la password per la chiave privata di crittografia, almeno 6 caratteri
echo ... 
openssl req -x509 -sha256 -days 730 -newkey rsa:2048 -keyout spid-oidc-check-op-enc.key -out spid-oidc-check-op-enc.crt
echo ... 
echo ... Ora si dovrà reinserire la password per rimuoverla dalla chiave
echo ...
openssl rsa -in spid-oidc-check-op-enc.key -out spid-oidc-check-op-enc.key
echo ...
echo ... Chiave e certificato di crittografia sono stati salvati rispettivamente in spid-oidc-check-op-enc.key e spid-oidc-check-op-enc.crt