echo ...
echo ... Questo comando serve a rinnovare la chiave ed il certificato utilizzabili da spid-oidc-check-op.
echo ... Verrà ora richiesto di inserire la password per la chiave privata, almeno 6 caratteri
echo ... 
openssl req -x509 -sha256 -days 730 -newkey rsa:2048 -keyout spid-oidc-check-op.key -out spid-oidc-check-op.crt
echo ... 
echo ... Ora si dovrà reinserire la password per rimuoverla dalla chiave
echo ...
openssl rsa -in spid-oidc-check-op.key -out spid-oidc-check-op.key
echo ...
echo ... Chiave e certificato sono stati salvati rispettivamente in spid-oidc-check-op.key e spid-oidc-check-op.crt
