echo ...
echo ... Questo comando serve a rinnovare la chiave ed il certificato di firma e di criptografica utilizzati da attribute authority implementata in spid-oidc-check-op.
echo ... Verrà ora richiesto di inserire la password per la chiave privata di firma, almeno 6 caratteri
echo ... 
openssl req -x509 -sha256 -days 730 -newkey rsa:2048 -keyout attribute-authority-sig.key -out attribute-authority-sig.crt
echo ... 
echo ... Ora si dovrà reinserire la password per rimuoverla dalla chiave
echo ...
openssl rsa -in attribute-authority-sig.key -out attribute-authority-sig.key
echo ...
echo ... Chiave e certificato di firma sono stati salvati rispettivamente in attribute-authority-sig.key e attribute-authority-sig.crt
echo ...
echo ...
echo ... Verrà ora richiesto di inserire la password per la chiave privata di crittografia, almeno 6 caratteri
echo ... 
openssl req -x509 -sha256 -days 730 -newkey rsa:2048 -keyout attribute-authority-enc.key -out attribute-authority-enc.crt
echo ... 
echo ... Ora si dovrà reinserire la password per rimuoverla dalla chiave
echo ...
openssl rsa -in attribute-authority-enc.key -out attribute-authority-enc.key
echo ...
echo ... Chiave e certificato di crittografia sono stati salvati rispettivamente in attribute-authority-enc.key e attribute-authority-enc.crt

