sequenceDiagram
    participant User
    participant RP
    participant OP
    User->>RP: OP selection
    RP-->>+User: 
    User-->>-OP: invalid authentication request
    OP-->>+User: 
    User-->>-RP: error authentication response
